import { Router } from 'express';
import { requireAuth, requireFaculty } from '../middleware/auth';

import * as Ctrl0 from '../controllers/faculty/analytics_charts__type_';
import * as Ctrl1 from '../controllers/faculty/analytics_concept-gap_export';
import * as Ctrl2 from '../controllers/faculty/analytics_concept-gap_insights';
import * as Ctrl3 from '../controllers/faculty/analytics_concept-gap';
import * as Ctrl4 from '../controllers/faculty/analytics_concept-gap_trend';
import * as Ctrl5 from '../controllers/faculty/analytics_concept-gaps';
import * as Ctrl6 from '../controllers/faculty/analytics_dashboard-summary';
import * as Ctrl7 from '../controllers/faculty/analytics_reports_attendance';
import * as Ctrl8 from '../controllers/faculty/analytics_reports_understanding';
import * as Ctrl9 from '../controllers/faculty/analytics_sessions__id_';
import * as Ctrl10 from '../controllers/faculty/analytics_sessions';
import * as Ctrl11 from '../controllers/faculty/profile_dashboard';
import * as Ctrl12 from '../controllers/faculty/profile_password';
import * as Ctrl13 from '../controllers/faculty/profile';
import * as Ctrl14 from '../controllers/faculty/profile_subjects';
import * as Ctrl15 from '../controllers/faculty/pulse-sessions__id__archive';
import * as Ctrl16 from '../controllers/faculty/pulse-sessions__id__close';
import * as Ctrl17 from '../controllers/faculty/pulse-sessions__id__code';
import * as Ctrl18 from '../controllers/faculty/pulse-sessions__id__generate-code';
import * as Ctrl19 from '../controllers/faculty/pulse-sessions__id__generate-qr';
import * as Ctrl20 from '../controllers/faculty/pulse-sessions__id__live';
import * as Ctrl21 from '../controllers/faculty/pulse-sessions__id__publish';
import * as Ctrl22 from '../controllers/faculty/pulse-sessions__id__qr-code';
import * as Ctrl23 from '../controllers/faculty/pulse-sessions__id_';
import * as Ctrl24 from '../controllers/faculty/pulse-sessions__id__start';
import * as Ctrl25 from '../controllers/faculty/pulse-sessions__id__status__action_';
import * as Ctrl26 from '../controllers/faculty/pulse-sessions__id__status';
import * as Ctrl27 from '../controllers/faculty/pulse-sessions__id__summary';
import * as Ctrl28 from '../controllers/faculty/pulse-sessions__id__timer__action_';
import * as Ctrl29 from '../controllers/faculty/pulse-sessions__id__timer';
import * as Ctrl30 from '../controllers/faculty/pulse-sessions';
import * as Ctrl31 from '../controllers/faculty/pulse-sessions_summary';
import * as Ctrl32 from '../controllers/faculty/subjects__id__outcomes__coId_';
import * as Ctrl33 from '../controllers/faculty/subjects__id__outcomes';
import * as Ctrl34 from '../controllers/faculty/subjects__id_';
import * as Ctrl35 from '../controllers/faculty/subjects__id__syllabus';
import * as Ctrl36 from '../controllers/faculty/subjects__id__units__unitId_';
import * as Ctrl37 from '../controllers/faculty/subjects__id__units__unitId__topics__topicId_';
import * as Ctrl38 from '../controllers/faculty/subjects__id__units__unitId__topics';
import * as Ctrl39 from '../controllers/faculty/subjects__id__units';
import * as Ctrl40 from '../controllers/faculty/subjects';

const router = Router();

router.use(requireAuth, requireFaculty);

router.get('/analytics/charts/:type', Ctrl0.GET);
router.get('/analytics/concept-gap/export', Ctrl1.GET);
router.get('/analytics/concept-gap/insights', Ctrl2.GET);
router.get('/analytics/concept-gap', Ctrl3.GET);
router.get('/analytics/concept-gap/trend', Ctrl4.GET);
router.get('/analytics/concept-gaps', Ctrl5.GET);
router.get('/analytics/dashboard-summary', Ctrl6.GET);
router.get('/analytics/reports/attendance', Ctrl7.GET);
router.get('/analytics/reports/understanding', Ctrl8.GET);
router.get('/analytics/sessions/:id', Ctrl9.GET);
router.get('/analytics/sessions', Ctrl10.GET);
router.get('/profile/dashboard', Ctrl11.GET);
router.post('/profile/password', Ctrl12.POST);
router.put('/profile/password', Ctrl12.PUT);
router.get('/profile', Ctrl13.GET);
router.put('/profile', Ctrl13.PUT);
router.patch('/profile', Ctrl13.PATCH);
router.get('/profile/subjects', Ctrl14.GET);
router.post('/pulse-sessions/:id/archive', Ctrl15.POST);
router.post('/pulse-sessions/:id/close', Ctrl16.POST);
router.get('/pulse-sessions/:id/code', Ctrl17.GET);
router.post('/pulse-sessions/:id/code', Ctrl17.POST);
router.put('/pulse-sessions/:id/code', Ctrl17.PUT);
router.post('/pulse-sessions/:id/generate-code', Ctrl18.POST);
router.post('/pulse-sessions/:id/generate-qr', Ctrl19.POST);
router.get('/pulse-sessions/:id/live', Ctrl20.GET);
router.post('/pulse-sessions/:id/publish', Ctrl21.POST);
router.get('/pulse-sessions/:id/qr-code', Ctrl22.GET);
router.post('/pulse-sessions/:id/qr-code', Ctrl22.POST);
router.get('/pulse-sessions/:id', Ctrl23.GET);
router.put('/pulse-sessions/:id', Ctrl23.PUT);
router.delete('/pulse-sessions/:id', Ctrl23.DELETE);
router.post('/pulse-sessions/:id/start', Ctrl24.POST);
router.post('/pulse-sessions/:id/status/:action', Ctrl25.POST);
router.get('/pulse-sessions/:id/status', Ctrl26.GET);
router.get('/pulse-sessions/:id/summary', Ctrl27.GET);
router.post('/pulse-sessions/:id/timer/:action', Ctrl28.POST);
router.get('/pulse-sessions/:id/timer', Ctrl29.GET);
router.get('/pulse-sessions', Ctrl30.GET);
router.post('/pulse-sessions', Ctrl30.POST);
router.get('/pulse-sessions/summary', Ctrl31.GET);
router.put('/subjects/:id/outcomes/:coId', Ctrl32.PUT);
router.delete('/subjects/:id/outcomes/:coId', Ctrl32.DELETE);
router.post('/subjects/:id/outcomes', Ctrl33.POST);
router.get('/subjects/:id', Ctrl34.GET);
router.put('/subjects/:id', Ctrl34.PUT);
router.delete('/subjects/:id', Ctrl34.DELETE);
router.post('/subjects/:id/syllabus', Ctrl35.POST);
router.delete('/subjects/:id/syllabus', Ctrl35.DELETE);
router.put('/subjects/:id/units/:unitId', Ctrl36.PUT);
router.delete('/subjects/:id/units/:unitId', Ctrl36.DELETE);
router.put('/subjects/:id/units/:unitId/topics/:topicId', Ctrl37.PUT);
router.delete('/subjects/:id/units/:unitId/topics/:topicId', Ctrl37.DELETE);
router.post('/subjects/:id/units/:unitId/topics', Ctrl38.POST);
router.post('/subjects/:id/units', Ctrl39.POST);
router.get('/subjects', Ctrl40.GET);
router.post('/subjects', Ctrl40.POST);

export default router;
